# 프로덕션용 Docker Compose 설정
version: '3.8'

services:
  # Next.js 프론트엔드
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription-nextjs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://django:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - django
    restart: unless-stopped

  # Django 백엔드
  django:
    build:
      context: ./backend-django
      dockerfile: Dockerfile
    container_name: subscription-django
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///db.sqlite3}
    ports:
      - "8000:8000"
    volumes:
      - django_data:/app/db
    restart: unless-stopped

volumes:
  django_data:

